/**
 * These are the states that the mqtt client can be in
 */
export const MQTT_STATE = {
  // Make sure these match the values defined on the device firmware in `helpers.h`
  CONNECTION_TIMEOUT: 'MQTT_STATE_CONNECTION_TIMEOUT',
  CONNECTION_LOST: 'MQTT_STATE_CONNECTION_LOST',
  CONNECT_FAILED: 'MQTT_STATE_CONNECT_FAILED',
  DISCONNECTED: 'MQTT_STATE_DISCONNECTED',
  CONNECTED: 'MQTT_STATE_CONNECTED',
  CONNECT_BAD_PROTOCOL: 'MQTT_STATE_CONNECT_BAD_PROTOCOL',
  CONNECT_BAD_CLIENT_ID: 'MQTT_STATE_CONNECT_BAD_CLIENT_ID',
  CONNECT_UNAVAILABLE: 'MQTT_STATE_CONNECT_UNAVAILABLE',
  CONNECT_BAD_CREDENTIALS: 'MQTT_STATE_CONNECT_BAD_CREDENTIALS',
  CONNECT_UNAUTHORIZED: 'MQTT_STATE_CONNECT_UNAUTHORIZED',
  CONFIG_ERROR: 'MQTT_STATE_CONFIG_ERROR',
} as const;
export type MQTT_STATE = typeof MQTT_STATE;
export type AN_MQTT_STATE = MQTT_STATE[keyof MQTT_STATE];

export const MQTTStateDescriptionMap: { [K in AN_MQTT_STATE]: string } = {
  [MQTT_STATE.CONNECTION_TIMEOUT]: 'Connect Timeout',
  [MQTT_STATE.CONNECTION_LOST]: 'Connection Lost',
  [MQTT_STATE.CONNECT_FAILED]: 'Connection Failed',
  [MQTT_STATE.DISCONNECTED]: 'Disconnected',
  [MQTT_STATE.CONNECTED]: 'Connected',
  [MQTT_STATE.CONNECT_BAD_PROTOCOL]: 'Bad Protocol',
  [MQTT_STATE.CONNECT_BAD_CLIENT_ID]: 'Bad Client ID',
  [MQTT_STATE.CONNECT_UNAVAILABLE]: 'MQTT Broker Unavailable',
  [MQTT_STATE.CONNECT_BAD_CREDENTIALS]: 'Bad Credentials',
  [MQTT_STATE.CONNECT_UNAUTHORIZED]: 'Unauthorized',
  [MQTT_STATE.CONFIG_ERROR]: 'Configuration Error',
};
